# Generated by Django 4.1.7 on 2023-03-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True, max_length=75, unique=True)),
                ('pub_date', models.DateField()),
                ('author', models.TextField(max_length=75)),
                ('description', models.TextField(max_length=175)),
                ('category', models.ManyToManyField(to='books.category')),
            ],
        ),
    ]
